#!/usr/bin/env bash
# Print "Best School" 10 times with a while loop
# but for the 9th loop, display "Best School" and then "Hi"

i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi

	((i++))
done
