#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59

i=0
h=0
while [ $i -le 60 ]
do 
	if(( i -eq 60 ))
	then
	((h++))
	echo "Hour: $h"
  	i=0
	else 
	echo "$i"
	((i++))
done
