#!/usr/bin/env bash
# Bash script that displays the content of working direcotry
# in list format where only part of the name is displayed
# after the first dash

for i in *
do
	echo "$i" | cut -f 1 -d '-'
done 
